spring.cloud.stream:
  function:
    definition: domainProcessor # method name which will be called
  bindings:
    domainProcessor-in-0:
      destination: web-domain # messages will be read from this topic
    domainProcessor-out-0:
      destination: active.web-domains # messages will be put on this topic
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091 # broker 1
        - localhost:9092 # broker 2